Azadi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AzadiApp.urls')),
]

AzadiApp/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser

# Create your models here.

coordinates_scale = 1000000

ATTACK_CHOICES = (
    ('p', "simulated attack"),
    ('f', "fall detected"),
    ('h', "heartrate spike"),
    ('o', "Outside Range"),
)

class AppUser(AbstractUser):
    phone = models.CharField(max_length=13, null=True)

class Watch(models.Model):
    id = models.IntegerField(unique=True, primary_key=True)
    owner = models.ForeignKey(AppUser, related_name='watch', on_delete=models.CASCADE)
    last_location = models.CharField(max_length=250, null=True, default=None)
    full_location = models.TextField(null=True, default=None)
    type_of_attack = models.CharField(max_length=2, choices=ATTACK_CHOICES, null=True)
    trusted_users = models.ManyToManyField(AppUser, related_name='watches')
    home_latitude = models.BigIntegerField(null=True)
    home_longitude = models.BigIntegerField(null=True)
    track_location = models.BooleanField(default=False)
    excercise_mode = models.BooleanField(default=False)

    def get_home_coordinates(self):
        if self.home_latitude and self.home_longitude:
            return self.home_latitude/coordinates_scale, self.home_longitude/coordinates_scale
        else:
            return None

    def set_home_coordinates(self, x, y):
        self.home_latitude = x*coordinates_scale
        self.home_longitude = y*coordinates_scale

class History(models.Model):
    watch = models.ForeignKey(Watch, related_name='history', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    latitude = models.BigIntegerField(null=True)
    longitude = models.BigIntegerField(null=True)
    heartrate = models.IntegerField(null=True)
    location_requested = models.BooleanField(default=False)

    def get_coordinates(self):
        if self.latitude and self.longitude:
            return self.latitude/coordinates_scale, self.longitude/coordinates_scale
        else:
            return None

    def set_coordinates(self, x, y):
        self.latitude = x*coordinates_scale
        self.longitude = y*coordinates_scale

templates/full-data.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Watch Data{% endblock %}
{% block top %}

{% endblock %}

{% block heading %}Watch Data{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 card" style="margin-top:0;">
            <h3 style="margin-top:30px;margin-bottom:10px;font-weight: 350;border-bottom: 2px solid  #00bcd4;"> Watch ID: {{watch.id}} </h3>

            <span>Owner: {{watch_json.owner}}</span>
            <span>Location: {{watch.full_location}}</span>
            <span>Home: {{watch.get_home_coordinates.0}}, {{watch.get_home_coordinates.1}}</span><br>
            {% if watch.trusted_users.all.exists %}<span>Trusted Contacts: </span>{% endif %}
            <ul>
                {% for contact in watch.trusted_users.all %}
                <li>{{contact.username}}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1"></div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 card" style="margin-top:0; text-align:center">
            <canvas id="myChart"></canvas>
            <span style="display: block; font-weight: bold" class="pt-2"> Recent heart rate data</span>
        </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <table class="table"    >
                    <tr style="border-bottom: 2px solid #dbdbdb;">
                        <th>Timestamp</th>
                        <th>Heartrate</th>
                        <th>Latitude</th>
                        <th>Longitude</th>
                    </tr>
                {% for data in history %}
                    <tr style="border-bottom: 1px solid #dbdbdb;">
                        <td>{{data.timestamp|date:"M d, Y h:i:s A"}}</td>
                        <td>{{data.heartrate}}</td>
                        <td>{{data.get_coordinates.0}}</td>
                        <td>{{data.get_coordinates.1}}</td>
                    </tr>

                {% endfor %}
                </table>
            </div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.js"></script>
<script type="text/javascript">
    var ctx = document.getElementById("myChart");
    var myBarChart = new Chart(ctx, {
    type: 'line',
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        },
        responsive: false,
    },
    data: {
        datasets: [
            {
                data: {{heartrates}},
                label: "Heart Rate",
                borderColor: "red",
                hoverBackgroundColor: "blue",
                fill: false
            }
        ],
        labels: {{timestamps | safe}},
    }
});
    var chart = new ApexCharts(
    document.querySelector("#myChart"),
    options
);
chart.render();
</script>

{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}
{% block heading %}Dashboard{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-8 col-lg-6">
            Welcome!
        </div>
    </div>
</div>
{% endblock %}

templates/my_watches.html
{% extends 'base.html' %}
{% load static %}

{% block title %}My Watches{% endblock %}

{% block top %}
  <!-- HereMaps -->
  <script src="https://js.api.here.com/v3/3.1/mapsjs-core.js"
  type="text/javascript" charset="utf-8"></script>
  <script src="https://js.api.here.com/v3/3.1/mapsjs-service.js"
  type="text/javascript" charset="utf-8"></script>
  </script>

{% endblock %}

{% block heading %}My Watches{% endblock %}


{% block content %}
<div class="container">
        <h3 style="border-bottom:1.5px solid #f44336;font-weight:400;">Your Watches</h3>
        {% if success %}
            <div class="alert alert-success">Watch added!</div>
        {% endif %}
    <div class="row">
        <div class="col-xs-12 col-md-8 col-lg-6 card" style="height:230px;">
            <h3 style="border-bottom:1.5px solid #f44336;font-weight:400;margin-bottom:10px;">Enter watch ID to add</h3>
            <form method="POST">
                {% csrf_token %}
                <!-- <label for="id">Watch ID</label> -->
                <input type="text" name="id" placeholder="Watch ID"class="form-control" style="height:45px;background-image: linear-gradient(0deg,#00bcd4 2px,rgba(156,39,176,0) 0),linear-gradient(0deg,#d2d2d2 1px,hsla(0,0%,82%,0) 0);"><br>
                <button type="submit" class="btn btn-info">Submit</button>
            </form>
        </div>
    <!-- </div> -->
    <!-- <div class="row"> -->
        <div class="col-xs-12 col-lg-6">

        <!-- </div> -->
        {% for watch in watches %}
        <!-- <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6"> -->
            <div class="col-xs-12">
            <div class="card" style="padding: 0 0 0 0;">
                <div class="card-body" style="padding: 0 0 0 0;">

                    {% if watch.coordinates %}
                    <div style="width:540px; height:250px" class="card-img-top" id="map{{watch.id}}">
                    {% else %}
                    <div class="card-body pt-1 pl-2" style="width: 540px; height: 250px">No Location Available</div>
                    {% endif %}
                    </div>
                    <a href="{% url 'full-data' watch.id %}"><div class="card-title pt-2 pl-2 pb-1">
                            <div class="col-xs-4"><b>Watch ID: {{watch.id}}</b></div>
                            <div class="col-xs-4">Owner: {{watch.owner}} <a href="tel: {{watch.owner_phone}}"><i class="fa fa-phone"></i></a></div>
                            {% if watch.type_of_attack %}
                            <div class="col-xs-4">Status: <span style="color: red;">{{watch.get_type_of_attack_display}}</span></div>
                            {% else %}
                            <div class="col-xs-4">Status: <span style="color: rgb(85, 255, 0);">Safe</span></div>
                            {% endif %}
                            <!-- <div class="col-xs-4">
                                <label class="switch">
                                    <input type="checkbox" checked>
                                    <span class="slider round" ></span>
                                  </label>
                            </div> -->
                    </div></a>
                    <div class="card-text pl-2 pb-1 text-center">
                            <div>
                                <input type="checkbox" id="excerciseMode" {% if watch.excercise_mode %}checked{% endif %} onclick="toggleexcercisemode({{watch.id}})">
                                <label for="excerciseMode">Excercise Mode</label>
                            </div>
                        <button type="button" class="btn btn-danger" onclick="attack_pressed({{watch.id}})">{% if watch.type_of_attack %}Cancel{% else %}Simulate Attack{% endif %}</button>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

  <!-- HereMaps -->
  <script src="https://js.api.here.com/v3/3.1/mapsjs-core.js"
  type="text/javascript" charset="utf-8"></script>
  <script src="https://js.api.here.com/v3/3.1/mapsjs-service.js"
  type="text/javascript" charset="utf-8"></script>
  <!-- Custom JS -->

  <script type="text/javascript" charset="utf-8">
    attack_pressed = function(wid) {
        fetch(window.location.href.split('/').slice(0,3).join('/')+'/api/attack-pressed/'+wid.toString()).then(
            setTimeout(function(){ window.location.reload() }, 500)
        );
    }

    toggleexcercisemode = function(wid) {
        fetch(window.location.href.split('/').slice(0,3).join('/')+'/api/excercise-mode-toggle/'+wid.toString()).then(
            setTimeout(function(){ window.location.reload() }, 500)
        );
    }


    var platform = new H.service.Platform({
        'apikey': 'lQdCCkaHvK_RqYJqu0FX8UoJIU-pSX-s79deRCF2otA'
    });

    var geocoder = platform.getGeocodingService();

    // Obtain the default map types from the platform object:
    var defaultLayers = platform.createDefaultLayers();

        {% for watch in watches %}
        {% if watch.coordinates %}
        var map = new H.Map(
            document.getElementById('map{{watch.id}}'),
            defaultLayers.vector.normal.map,
            {
                zoom: 12,
                center: {lat: {{watch.coordinates.0}}, lng: {{watch.coordinates.1}}}
            }
        );

        // resize on window resize
        window.addEventListener('resize', function () {
            map.getViewPort().resize();
        });

        var animatedSvg =
        '<svg height="100" width="100"><circle cx="15" cy="15" r="10" stroke="black" stroke-width="3" fill="#00bcd4" /></svg>';

        // Create an icon object, an object with geographic coordinates and a marker:
        var icon = new H.map.DomIcon(animatedSvg),
            coords = {lat: {{watch.coordinates.0}}, lng: {{watch.coordinates.1}}},
            marker = new H.map.DomMarker(coords, {icon: icon});

        // Set map center and zoom, add the marker to the map:
        map.setCenter(coords);
        map.addObject(marker);

        {% endif %}
        {% endfor %}
  </script>
{% endblock %}